### ISSUE TITLE
Cgroup memory.limit_in_bytes == 9223372036854775807 or 9223372036854771712?

### ISSUE THREAD

**Issue by thorti1985** [cevich/autotest-docker#14]
Hello,
you defined in "subtests/docker_cli/run_cgroups/memory.py" the following:
"if cgroup_memory == 9223372036854775807:"

How you got this value? 
Because my if I start the container with "-m 0" the cgroup memory slice "memory.limit_in_bytes" shows the value 9223372036854771712 !

In Kernel 4.3 "include/linux/page_counter.h" defines PAGE_COUNTER_MAX with 2251799813685247

[ LONG_MAX / PAGE_SIZE =  9223372036854775807 /  4096 = 2251799813685247,..... which will be cut to 2251799813685247  ] 

```
#if BITS_PER_LONG == 32
#define PAGE_COUNTER_MAX LONG_MAX
#else
#define PAGE_COUNTER_MAX (LONG_MAX / PAGE_SIZE) 
#endif
```

And back to the memory limit 
 2251799813685247 * 4096 = 0x7FFFFFFFFFFFF000 = 9223372036854771712

So the value in the test should be 9223372036854771712 and not 9223372036854775807!?

**Comment by cevich** [comment]
Hi,

Were you not able to open the issue on the main project?
https://github.com/autotest/autotest-docker

I didn't write that particular test originally, but we did have a BZ open against docker about it if I recall, likely long since fixed.  In any case, docker's changed, and kernels change, and I haven't looked at this test in ages (though I run Docker Autotest w/in our CI environment several times daily).  

Curiously, the difference between the two is one-page, so I wonder if it wasn't set that way for some pythonic reason.

In any case, if you find the test operates as intended with the value you derived, I'd be happy to take a pull-request on it.

If you need help doing that, just let me know :)

**Comment by cevich** [comment]
This needs to be on autotest/autotest-docker please (if it's still an issue)
